# Cargo config file.
# See: https://doc.rust-lang.org/cargo/reference/config.html

# Environments variables set for all `cargo ...` commands.
[env]

# Scop down tracing, to filter out external lib tracing.
RUST_LOG = "web=debug"
