# Cargo config file.
# See: https://doc.rust-lang.org/cargo/reference/config.html

# Environments variables set for all `cargo ...` commands.
[env]

# Scop down tracing, to filter out external lib tracing.
RUST_LOG = "web=debug"

# -- Service Environment Variables
# IMPORTANT:
#    For cargo command only.
#    For deployed env, should be managed by container
#    (e.g., Kubernetes).

## -- Secrets
# Keys and passwords below are for localhost dev ONLY.
# e.g., "password" type of passwords.
# i.e., Encryption not needed.
POSTGRES_URL = "postgres://app_user:dev_only_pwd@db/app_db"

SERVICE_PWD_KEY = "eG_QXzBjNyyCOQZiUh3Y1mWBBFRHuReMKz9zQiBIifVjRQK33j12PHDSqgoJjqtOvkPRh1pvuQcj_urCJBvM6A"

SERVICE_TOKEN_KEY = "_WoBFFFjwUGnlG0lkDFV5l9mWvNs7FnMfHe9UHJheTCtuMUpuAc22fYmh-Y8iojvgr7j8NLTzFjBSB8nr8SDYg"

SERVICE_TOKEN_DURATION_SEC = "1800" # 30 minutes

## -- ConfigMap

# This willbe relative to cargo.toml
# In deployed images, probably use absolute path.
SERVICE_WEB_FOLDER = "web-folder/"
